# Form implementation generated from reading ui file '/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(833, 525)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/others - Chi1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 839, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/MainWindow.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(80, 50, 681, 371))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: none; /* Loại bỏ viền của QTabWidget */\n"
"    background-color: transparent; /* Đặt nền trong suốt cho pane */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background-color: #1a3c6d; /* Màu nền của các tab (xanh biển đậm) */\n"
"    color: white; /* Màu chữ trắng */\n"
"    border: 2px solid #1a3c6d; /* Viền của tab (xanh biển đậm) */\n"
"    border-radius: 0px; /* Không bo góc giữa các tab */\n"
"    padding: 10px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 0px; /* Loại bỏ khoảng cách bên phải giữa các tab */\n"
"}\n"
"\n"
"QTabBar::tab:first {\n"
"    border-top-left-radius: 10px; /* Bo tròn góc trái trên của tab đầu tiên */\n"
"    border-top-right-radius: 0px; /* Không bo tròn góc phải trên của tab đầu tiên */\n"
"}\n"
"\n"
"QTabBar::tab:last {\n"
"    border-top-right-radius: 10px; /* Bo tròn góc phải trên của tab cuối cùng */\n"
"    border-top-left-radius: 0px; /* Không bo tròn góc trái trên của tab cuối cùng */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background-color: #4a90e2; /* Màu nền của tab khi chọn (xanh biển nhạt hơn) */\n"
"    color: white; /* Màu chữ khi chọn (trắng) */\n"
"    border-color: #4a90e2; /* Viền của tab khi chọn (xanh biển nhạt hơn) */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background-color: #76d7c4; /* Màu nền của tab khi hover (xanh lá nhạt hơn) */\n"
"    border-color: #76d7c4; /* Viền của tab khi hover (xanh lá nhạt hơn) */\n"
"}\n"
"\n"
"/* Căn giữa QTabWidget */\n"
"QTabWidget {\n"
"    background-color: #ecf0f1; /* Màu nền của QTabWidget */\n"
"    border-radius: 10px; /* Bo tròn các góc của QTabWidget */\n"
"    padding: 5px;\n"
"    margin: 0 auto; /* Căn giữa QTabWidget */\n"
"    display: block; /* Đảm bảo QTabWidget được hiển thị như một block */\n"
"}\n"
"")
        self.tabWidget.setElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.tabWidget.setObjectName("tabWidget")
        self.tabOverview = QtWidgets.QWidget()
        self.tabOverview.setObjectName("tabOverview")
        self.lineEditTotalMoneyOut = QtWidgets.QLineEdit(parent=self.tabOverview)
        self.lineEditTotalMoneyOut.setGeometry(QtCore.QRect(170, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditTotalMoneyOut.setFont(font)
        self.lineEditTotalMoneyOut.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền màu xanh dương */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #b3e5fc; /* Màu nền xanh nhạt khi hover */\n"
"    border-color: #0288d1; /* Màu viền khi hover (xanh dương) */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #81d4fa; /* Màu nền xanh sáng khi focus */\n"
"    border-color: #0288d1; /* Màu viền khi focus (xanh dương) */\n"
"}\n"
"")
        self.lineEditTotalMoneyOut.setObjectName("lineEditTotalMoneyOut")
        self.label_9 = QtWidgets.QLabel(parent=self.tabOverview)
        self.label_9.setGeometry(QtCore.QRect(20, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.lineEditTotalMoneyIn = QtWidgets.QLineEdit(parent=self.tabOverview)
        self.lineEditTotalMoneyIn.setGeometry(QtCore.QRect(170, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditTotalMoneyIn.setFont(font)
        self.lineEditTotalMoneyIn.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #28a745; /* Viền màu xanh lá */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #d4edda; /* Màu nền khi hover (xanh lá nhạt) */\n"
"    border-color: #28a745; /* Màu viền khi hover (xanh lá) */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #c3e6cb; /* Màu nền khi focus (xanh lá sáng) */\n"
"    border-color: #218838; /* Màu viền khi focus (xanh lá đậm) */\n"
"}\n"
"")
        self.lineEditTotalMoneyIn.setObjectName("lineEditTotalMoneyIn")
        self.label_10 = QtWidgets.QLabel(parent=self.tabOverview)
        self.label_10.setGeometry(QtCore.QRect(20, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.tabOverview)
        self.label_11.setGeometry(QtCore.QRect(360, 190, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.lineEditTotalBalance = QtWidgets.QLineEdit(parent=self.tabOverview)
        self.lineEditTotalBalance.setGeometry(QtCore.QRect(490, 190, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditTotalBalance.setFont(font)
        self.lineEditTotalBalance.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #fbc02d; /* Viền màu vàng mặc định */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease, border-color 0.3s ease; /* Thêm hiệu ứng chuyển màu nền và viền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #fff59d; /* Màu nền vàng nhạt khi hover */\n"
"    border-color: #fbc02d; /* Viền vàng khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #fff176; /* Màu nền vàng sáng khi focus */\n"
"    border-color: #fbc02d; /* Viền vàng khi focus */\n"
"}\n"
"")
        self.lineEditTotalBalance.setObjectName("lineEditTotalBalance")
        self.lineEditWelcome = QtWidgets.QLineEdit(parent=self.tabOverview)
        self.lineEditWelcome.setGeometry(QtCore.QRect(60, 30, 551, 131))
        self.lineEditWelcome.setStyleSheet("    QLineEdit {\n"
"        font-family: \'Arial\', sans-serif; /* Phông chữ hiện đại */\n"
"        font-size: 35px; /* Kích thước chữ lớn và dễ nhìn */\n"
"        font-weight: bold; /* Làm đậm chữ */\n"
"        color: #ffffff; /* Màu chữ trắng */\n"
"        background-color: #3498db; /* Màu nền xanh dương */\n"
"        border: 3px solid #2980b9; /* Viền xanh đậm */\n"
"        border-radius: 20px; /* Bo tròn các góc */\n"
"        padding: 20px; /* Khoảng cách bên trong label */\n"
"        margin: 20px 0; /* Khoảng cách trên và dưới */\n"
"       text-align: center;\n"
"        text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.4); /* Hiệu ứng bóng cho chữ */\n"
"        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2); /* Bóng đổ xung quanh label */\n"
"    }\n"
"\n"
"    QLineEdit:hover {\n"
"        color: #f1c40f; /* Màu chữ khi hover (vàng) */\n"
"        background-color: #2980b9; /* Màu nền khi hover (xanh đậm) */\n"
"        border-color: #1f5d76; /* Màu viền khi hover (xanh đậm hơn) */\n"
"        box-shadow: 0 8px 10px rgba(0, 0, 0, 0.3); /* Tăng hiệu ứng bóng khi hover */\n"
"    }")
        self.lineEditWelcome.setText("")
        self.lineEditWelcome.setObjectName("lineEditWelcome")
        self.lineEditTotalSavings = QtWidgets.QLineEdit(parent=self.tabOverview)
        self.lineEditTotalSavings.setGeometry(QtCore.QRect(490, 240, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditTotalSavings.setFont(font)
        self.lineEditTotalSavings.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #fbc02d; /* Viền màu vàng mặc định */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease, border-color 0.3s ease; /* Thêm hiệu ứng chuyển màu nền và viền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #fff59d; /* Màu nền vàng nhạt khi hover */\n"
"    border-color: #fbc02d; /* Viền vàng khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #fff176; /* Màu nền vàng sáng khi focus */\n"
"    border-color: #fbc02d; /* Viền vàng khi focus */\n"
"}\n"
"")
        self.lineEditTotalSavings.setObjectName("lineEditTotalSavings")
        self.label_13 = QtWidgets.QLabel(parent=self.tabOverview)
        self.label_13.setGeometry(QtCore.QRect(360, 240, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tabOverview, "")
        self.tabNewTransaction = QtWidgets.QWidget()
        self.tabNewTransaction.setObjectName("tabNewTransaction")
        self.pushButtonSpending = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButtonSpending.setGeometry(QtCore.QRect(260, 220, 151, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSpending.setFont(font)
        self.pushButtonSpending.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonSpending.setObjectName("pushButtonSpending")
        self.pushButtonEarnings = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButtonEarnings.setGeometry(QtCore.QRect(70, 220, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonEarnings.setFont(font)
        self.pushButtonEarnings.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonEarnings.setObjectName("pushButtonEarnings")
        self.pushButtonSavings = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButtonSavings.setGeometry(QtCore.QRect(460, 220, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSavings.setFont(font)
        self.pushButtonSavings.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonSavings.setObjectName("pushButtonSavings")
        self.pushButton = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 151, 141))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none; /* Loại bỏ viền */\n"
"    color: #FFFFFF; /* Màu chữ trắng */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    padding: 10px 20px; /* Khoảng cách trong nút */\n"
"    border-radius: 5px; /* Bo tròn các góc của nút */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/Earnings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(150, 150))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 50, 151, 151))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none; /* Loại bỏ viền */\n"
"    color: #FFFFFF; /* Màu chữ trắng */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    padding: 10px 20px; /* Khoảng cách trong nút */\n"
"    border-radius: 5px; /* Bo tròn các góc của nút */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/spending1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(140, 140))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.tabNewTransaction)
        self.pushButton_3.setGeometry(QtCore.QRect(460, 50, 151, 141))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"    border: none; /* Loại bỏ viền */\n"
"    color: #FFFFFF; /* Màu chữ trắng */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    padding: 10px 20px; /* Khoảng cách trong nút */\n"
"    border-radius: 5px; /* Bo tròn các góc của nút */\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../images/savings1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon3)
        self.pushButton_3.setIconSize(QtCore.QSize(130, 130))
        self.pushButton_3.setObjectName("pushButton_3")
        self.tabWidget.addTab(self.tabNewTransaction, "")
        self.tabManagement = QtWidgets.QWidget()
        self.tabManagement.setObjectName("tabManagement")
        self.labelMoneyIn = QtWidgets.QLabel(parent=self.tabManagement)
        self.labelMoneyIn.setGeometry(QtCore.QRect(60, 30, 231, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.labelMoneyIn.setFont(font)
        self.labelMoneyIn.setObjectName("labelMoneyIn")
        self.labelMoneyOut = QtWidgets.QLabel(parent=self.tabManagement)
        self.labelMoneyOut.setGeometry(QtCore.QRect(380, 30, 241, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.labelMoneyOut.setFont(font)
        self.labelMoneyOut.setObjectName("labelMoneyOut")
        self.label_4 = QtWidgets.QLabel(parent=self.tabManagement)
        self.label_4.setGeometry(QtCore.QRect(90, 230, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("    QLabel {\n"
"        font-family: \'Arial\', sans-serif; /* Phông chữ hiện đại */\n"
"        font-size: 15px; /* Kích thước chữ lớn và dễ nhìn */\n"
"        font-weight: bold; /* Làm đậm chữ */\n"
"        color: #ffffff; /* Màu chữ trắng */\n"
"        background-color: #3498db; /* Màu nền xanh dương */\n"
"        border: 3px solid #2980b9; /* Viền xanh đậm */\n"
"        border-radius: 20px; /* Bo tròn các góc */\n"
"        padding: 20px; /* Khoảng cách bên trong label */\n"
"        text-align: center; /* Căn giữa chữ */\n"
"        margin: 20px 0; /* Khoảng cách trên và dưới */\n"
"        text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.4); /* Hiệu ứng bóng cho chữ */\n"
"        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2); /* Bóng đổ xung quanh label */\n"
"    }\n"
"\n"
"    QLabel:hover {\n"
"        color: #f1c40f; /* Màu chữ khi hover (vàng) */\n"
"        background-color: #2980b9; /* Màu nền khi hover (xanh đậm) */\n"
"        border-color: #1f5d76; /* Màu viền khi hover (xanh đậm hơn) */\n"
"        box-shadow: 0 8px 10px rgba(0, 0, 0, 0.3); /* Tăng hiệu ứng bóng khi hover */\n"
"    }")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.tabManagement)
        self.label_5.setGeometry(QtCore.QRect(440, 230, 141, 101))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("    QLabel {\n"
"        font-family: \'Arial\', sans-serif; /* Phông chữ hiện đại */\n"
"        font-size: 15px; /* Kích thước chữ lớn và dễ nhìn */\n"
"        font-weight: bold; /* Làm đậm chữ */\n"
"        color: #ffffff; /* Màu chữ trắng */\n"
"        background-color: #3498db; /* Màu nền xanh dương */\n"
"        border: 3px solid #2980b9; /* Viền xanh đậm */\n"
"        border-radius: 20px; /* Bo tròn các góc */\n"
"        padding: 20px; /* Khoảng cách bên trong label */\n"
"        text-align: center; /* Căn giữa chữ */\n"
"        margin: 20px 0; /* Khoảng cách trên và dưới */\n"
"        text-shadow: 3px 3px 10px rgba(0, 0, 0, 0.4); /* Hiệu ứng bóng cho chữ */\n"
"        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2); /* Bóng đổ xung quanh label */\n"
"    }\n"
"\n"
"    QLabel:hover {\n"
"        color: #f1c40f; /* Màu chữ khi hover (vàng) */\n"
"        background-color: #2980b9; /* Màu nền khi hover (xanh đậm) */\n"
"        border-color: #1f5d76; /* Màu viền khi hover (xanh đậm hơn) */\n"
"        box-shadow: 0 8px 10px rgba(0, 0, 0, 0.3); /* Tăng hiệu ứng bóng khi hover */\n"
"    }")
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tabManagement, "")
        self.tabHistory = QtWidgets.QWidget()
        self.tabHistory.setObjectName("tabHistory")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.tabHistory)
        self.tableWidget.setGeometry(QtCore.QRect(10, 40, 401, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 4, item)
        self.pushButtonMoneyIn = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonMoneyIn.setGeometry(QtCore.QRect(30, 250, 101, 41))
        self.pushButtonMoneyIn.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"")
        self.pushButtonMoneyIn.setObjectName("pushButtonMoneyIn")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonDelete.setGeometry(QtCore.QRect(480, 260, 91, 31))
        self.pushButtonDelete.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"")
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonMoneyOut = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonMoneyOut.setGeometry(QtCore.QRect(140, 250, 101, 41))
        self.pushButtonMoneyOut.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"")
        self.pushButtonMoneyOut.setObjectName("pushButtonMoneyOut")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonClear.setGeometry(QtCore.QRect(380, 260, 91, 31))
        self.pushButtonClear.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.label_6 = QtWidgets.QLabel(parent=self.tabHistory)
        self.label_6.setGeometry(QtCore.QRect(430, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditNo = QtWidgets.QLineEdit(parent=self.tabHistory)
        self.lineEditNo.setGeometry(QtCore.QRect(490, 50, 181, 31))
        self.lineEditNo.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền màu xanh dương */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #b3e5fc; /* Màu nền xanh nhạt khi hover */\n"
"    border-color: #0288d1; /* Màu viền khi hover (xanh dương) */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #81d4fa; /* Màu nền xanh sáng khi focus */\n"
"    border-color: #0288d1; /* Màu viền khi focus (xanh dương) */\n"
"}\n"
"\n"
"")
        self.lineEditNo.setObjectName("lineEditNo")
        self.label_7 = QtWidgets.QLabel(parent=self.tabHistory)
        self.label_7.setGeometry(QtCore.QRect(430, 100, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.lineEditDate = QtWidgets.QLineEdit(parent=self.tabHistory)
        self.lineEditDate.setGeometry(QtCore.QRect(490, 90, 181, 31))
        self.lineEditDate.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #28a745; /* Viền màu xanh lá */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #d4edda; /* Màu nền khi hover (xanh lá nhạt) */\n"
"    border-color: #28a745; /* Màu viền khi hover (xanh lá) */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #c3e6cb; /* Màu nền khi focus (xanh lá sáng) */\n"
"    border-color: #218838; /* Màu viền khi focus (xanh lá đậm) */\n"
"}\n"
"")
        self.lineEditDate.setObjectName("lineEditDate")
        self.lineEditAmount = QtWidgets.QLineEdit(parent=self.tabHistory)
        self.lineEditAmount.setGeometry(QtCore.QRect(490, 130, 181, 31))
        self.lineEditAmount.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #fbc02d; /* Viền màu vàng mặc định */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease, border-color 0.3s ease; /* Thêm hiệu ứng chuyển màu nền và viền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #fff59d; /* Màu nền vàng nhạt khi hover */\n"
"    border-color: #fbc02d; /* Viền vàng khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #fff176; /* Màu nền vàng sáng khi focus */\n"
"    border-color: #fbc02d; /* Viền vàng khi focus */\n"
"}\n"
"")
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.label_8 = QtWidgets.QLabel(parent=self.tabHistory)
        self.label_8.setGeometry(QtCore.QRect(430, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_12 = QtWidgets.QLabel(parent=self.tabHistory)
        self.label_12.setGeometry(QtCore.QRect(430, 180, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.radioButtonMoneyIn = QtWidgets.QRadioButton(parent=self.tabHistory)
        self.radioButtonMoneyIn.setGeometry(QtCore.QRect(520, 170, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonMoneyIn.setFont(font)
        self.radioButtonMoneyIn.setObjectName("radioButtonMoneyIn")
        self.radioButtonMoneyOut = QtWidgets.QRadioButton(parent=self.tabHistory)
        self.radioButtonMoneyOut.setGeometry(QtCore.QRect(520, 200, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButtonMoneyOut.setFont(font)
        self.radioButtonMoneyOut.setObjectName("radioButtonMoneyOut")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonSave.setGeometry(QtCore.QRect(580, 260, 91, 31))
        self.pushButtonSave.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonSavings_2 = QtWidgets.QPushButton(parent=self.tabHistory)
        self.pushButtonSavings_2.setGeometry(QtCore.QRect(250, 250, 101, 41))
        self.pushButtonSavings_2.setStyleSheet("/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 8px 16px; /* Giảm khoảng cách giữa văn bản và viền */\n"
"    font-size: 12px; /* Giảm kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"")
        self.pushButtonSavings_2.setObjectName("pushButtonSavings_2")
        self.tabWidget.addTab(self.tabHistory, "")
        self.tabSetting = QtWidgets.QWidget()
        self.tabSetting.setObjectName("tabSetting")
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=self.tabSetting)
        self.pushButtonLogOut.setGeometry(QtCore.QRect(200, 250, 141, 51))
        self.pushButtonLogOut.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.pushButtonReset = QtWidgets.QPushButton(parent=self.tabSetting)
        self.pushButtonReset.setGeometry(QtCore.QRect(360, 250, 141, 51))
        self.pushButtonReset.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.pushButtonUserGuide = QtWidgets.QPushButton(parent=self.tabSetting)
        self.pushButtonUserGuide.setGeometry(QtCore.QRect(20, 250, 161, 51))
        self.pushButtonUserGuide.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonUserGuide.setObjectName("pushButtonUserGuide")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.tabSetting)
        self.pushButtonClose.setGeometry(QtCore.QRect(520, 250, 141, 51))
        self.pushButtonClose.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.tabWidget.addTab(self.tabSetting, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "Total money out:"))
        self.label_10.setText(_translate("MainWindow", "Total money in:"))
        self.label_11.setText(_translate("MainWindow", "Total Balance:"))
        self.label_13.setText(_translate("MainWindow", "Total Savings:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOverview), _translate("MainWindow", "Overview"))
        self.pushButtonSpending.setText(_translate("MainWindow", "Spending"))
        self.pushButtonEarnings.setText(_translate("MainWindow", "Earnings"))
        self.pushButtonSavings.setText(_translate("MainWindow", "Savings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNewTransaction), _translate("MainWindow", "New Transaction"))
        self.labelMoneyIn.setText(_translate("MainWindow", "Pie chart 1"))
        self.labelMoneyOut.setText(_translate("MainWindow", "Pie chart 2"))
        self.label_4.setText(_translate("MainWindow", "MONEY IN"))
        self.label_5.setText(_translate("MainWindow", "MONEY OUT"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabManagement), _translate("MainWindow", "Management"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Category"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Category Detail"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Amount"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "01"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "01/01/2025"))
        item = self.tableWidget.item(0, 4)
        item.setText(_translate("MainWindow", "Shopping"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "02"))
        item = self.tableWidget.item(1, 2)
        item.setText(_translate("MainWindow", "31/12/2024"))
        item = self.tableWidget.item(1, 4)
        item.setText(_translate("MainWindow", "Food & Drink"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "03"))
        item = self.tableWidget.item(2, 2)
        item.setText(_translate("MainWindow", "04/02/2025"))
        item = self.tableWidget.item(2, 4)
        item.setText(_translate("MainWindow", "Invoice"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "04"))
        item = self.tableWidget.item(3, 2)
        item.setText(_translate("MainWindow", "01/12/2024"))
        item = self.tableWidget.item(3, 4)
        item.setText(_translate("MainWindow", "Salary"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "05"))
        item = self.tableWidget.item(4, 2)
        item.setText(_translate("MainWindow", "12/12/2024"))
        item = self.tableWidget.item(4, 4)
        item.setText(_translate("MainWindow", "Shopping "))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.pushButtonMoneyIn.setText(_translate("MainWindow", "Money in"))
        self.pushButtonDelete.setText(_translate("MainWindow", "Delete"))
        self.pushButtonMoneyOut.setText(_translate("MainWindow", "Money out"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear"))
        self.label_6.setText(_translate("MainWindow", "No. :"))
        self.label_7.setText(_translate("MainWindow", "Date: "))
        self.label_8.setText(_translate("MainWindow", "Amount:"))
        self.label_12.setText(_translate("MainWindow", "Category:"))
        self.radioButtonMoneyIn.setText(_translate("MainWindow", "Money In"))
        self.radioButtonMoneyOut.setText(_translate("MainWindow", "Money Out"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonSavings_2.setText(_translate("MainWindow", "Savings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistory), _translate("MainWindow", "History"))
        self.pushButtonLogOut.setText(_translate("MainWindow", "Log out"))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset"))
        self.pushButtonUserGuide.setText(_translate("MainWindow", "User Guide"))
        self.pushButtonClose.setText(_translate("MainWindow", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSetting), _translate("MainWindow", "Setting"))
