# Form implementation generated from reading ui file '/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/WindowSpending.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(837, 525)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 839, 471))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(11, 37, 114);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/Spending.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(160, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButtonMoving = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMoving.setGeometry(QtCore.QRect(250, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonMoving.setFont(font)
        self.pushButtonMoving.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButtonMoving.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/moving1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonMoving.setIcon(icon)
        self.pushButtonMoving.setIconSize(QtCore.QSize(80, 80))
        self.pushButtonMoving.setObjectName("pushButtonMoving")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 200, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.pushButtonShopping = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonShopping.setGeometry(QtCore.QRect(380, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonShopping.setFont(font)
        self.pushButtonShopping.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButtonShopping.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/shopping1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonShopping.setIcon(icon1)
        self.pushButtonShopping.setIconSize(QtCore.QSize(80, 80))
        self.pushButtonShopping.setObjectName("pushButtonShopping")
        self.pushButtonFoodDrink = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonFoodDrink.setGeometry(QtCore.QRect(120, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonFoodDrink.setFont(font)
        self.pushButtonFoodDrink.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButtonFoodDrink.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/snapedit_1740885333816.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonFoodDrink.setIcon(icon2)
        self.pushButtonFoodDrink.setIconSize(QtCore.QSize(80, 80))
        self.pushButtonFoodDrink.setObjectName("pushButtonFoodDrink")
        self.lineEditAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAmount.setGeometry(QtCore.QRect(310, 120, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditAmount.setFont(font)
        self.lineEditAmount.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #ffeb3b; /* Màu vàng nền khi hover */\n"
"    border-color: #ffcc00; /* Màu viền khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #ffeb3b; /* Màu vàng nền khi focus */\n"
"    border-color: #ffcc00; /* Màu viền khi focus */\n"
"}\n"
"")
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.pushButtonInvoice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonInvoice.setGeometry(QtCore.QRect(510, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonInvoice.setFont(font)
        self.pushButtonInvoice.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButtonInvoice.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/invoic1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonInvoice.setIcon(icon3)
        self.pushButtonInvoice.setIconSize(QtCore.QSize(80, 80))
        self.pushButtonInvoice.setObjectName("pushButtonInvoice")
        self.pushButtonOthers = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOthers.setGeometry(QtCore.QRect(640, 240, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.pushButtonOthers.setFont(font)
        self.pushButtonOthers.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButtonOthers.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/../images/others - Chi1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonOthers.setIcon(icon4)
        self.pushButtonOthers.setIconSize(QtCore.QSize(80, 80))
        self.pushButtonOthers.setObjectName("pushButtonOthers")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(170, 360, 113, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(570, 360, 113, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.radioButtonFoodDrink = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonFoodDrink.setGeometry(QtCore.QRect(90, 330, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonFoodDrink.setFont(font)
        self.radioButtonFoodDrink.setStyleSheet("color: rgb(11, 37, 114);")
        self.radioButtonFoodDrink.setObjectName("radioButtonFoodDrink")
        self.radioButtonMoving = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonMoving.setGeometry(QtCore.QRect(250, 330, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonMoving.setFont(font)
        self.radioButtonMoving.setStyleSheet("color: rgb(11, 37, 114);")
        self.radioButtonMoving.setObjectName("radioButtonMoving")
        self.radioButtonShopping = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonShopping.setGeometry(QtCore.QRect(370, 330, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonShopping.setFont(font)
        self.radioButtonShopping.setStyleSheet("color: rgb(11, 37, 114);\n"
"")
        self.radioButtonShopping.setObjectName("radioButtonShopping")
        self.radioButtonInvoice = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonInvoice.setGeometry(QtCore.QRect(500, 330, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonInvoice.setFont(font)
        self.radioButtonInvoice.setStyleSheet("color: rgb(11, 37, 114);\n"
"")
        self.radioButtonInvoice.setObjectName("radioButtonInvoice")
        self.radioButtonOthers = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonOthers.setGeometry(QtCore.QRect(640, 330, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonOthers.setFont(font)
        self.radioButtonOthers.setStyleSheet("color: rgb(11, 37, 114);\n"
"")
        self.radioButtonOthers.setObjectName("radioButtonOthers")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(370, 360, 113, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(310, 170, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #f0f0f0; /* Màu nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền mặc định */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    background-color: #a5d6a7; /* Màu nền khi hover (xanh lá nhạt) */\n"
"    border-color: #66bb6a; /* Màu viền khi hover (xanh lá) */\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    background-color: #c8e6c9; /* Màu nền khi focus (xanh lá nhạt) */\n"
"    border-color: #388e3c; /* Màu viền khi focus (xanh lá đậm) */\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 837, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "Date:"))
        self.label_5.setText(_translate("MainWindow", "Amount:"))
        self.label_7.setText(_translate("MainWindow", "Category:"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear "))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
        self.radioButtonFoodDrink.setText(_translate("MainWindow", "Food and drink"))
        self.radioButtonMoving.setText(_translate("MainWindow", "Moving"))
        self.radioButtonShopping.setText(_translate("MainWindow", "Shopping"))
        self.radioButtonInvoice.setText(_translate("MainWindow", "Invoice"))
        self.radioButtonOthers.setText(_translate("MainWindow", "Others"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
