# Form implementation generated from reading ui file '/Users/huynhthaonhi/PycharmProjects/MoneyTracker/MONEY_TRACK/ui/WindowEarning.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 491)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 839, 471))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../images/Earnings.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(210, 240, 91, 81))
        self.pushButton1.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButton1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../images/salary1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton1.setIcon(icon)
        self.pushButton1.setIconSize(QtCore.QSize(70, 70))
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(380, 240, 91, 81))
        self.pushButton2.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"")
        self.pushButton2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../images/thu╠¢o╠¢╠ëng1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton2.setIcon(icon1)
        self.pushButton2.setIconSize(QtCore.QSize(70, 70))
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(540, 240, 91, 81))
        self.pushButton3.setStyleSheet("QPushButton {\n"
"    background-color: #0066cc; /* Màu nền mặc định */\n"
"    color: white; /* Màu chữ */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 10px 20px; /* Khoảng cách bên trong */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    background-image: url(\'image_path_here\'); /* Đặt hình ảnh làm nền */\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    width: 150px; /* Điều chỉnh kích thước */\n"
"    height: 50px;\n"
"    transition: background-color 0.3s ease; /* Hiệu ứng chuyển màu mượt mà */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #ffcc00; /* Nền màu vàng khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff9900; /* Nền màu cam khi nhấn */\n"
"}\n"
"\n"
"")
        self.pushButton3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../images/other-thu1.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton3.setIcon(icon2)
        self.pushButton3.setIconSize(QtCore.QSize(70, 70))
        self.pushButton3.setObjectName("pushButton3")
        self.lineEditAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditAmount.setGeometry(QtCore.QRect(290, 120, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lineEditAmount.setFont(font)
        self.lineEditAmount.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background 0.3s ease; /* Thêm hiệu ứng chuyển màu nền */\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    background-color: #ffeb3b; /* Màu vàng nền khi hover */\n"
"    border-color: #ffcc00; /* Màu viền khi hover */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    background-color: #ffeb3b; /* Màu vàng nền khi focus */\n"
"    border-color: #ffcc00; /* Màu viền khi focus */\n"
"}\n"
"")
        self.lineEditAmount.setObjectName("lineEditAmount")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 130, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 170, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 200, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(0, 0, 831, 461))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../images/Earnings.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.radioButtonSalary = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonSalary.setGeometry(QtCore.QRect(210, 330, 100, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonSalary.setFont(font)
        self.radioButtonSalary.setStyleSheet("color: rgb(11, 37, 114);")
        self.radioButtonSalary.setObjectName("radioButtonSalary")
        self.radioButtonAllowance = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonAllowance.setGeometry(QtCore.QRect(370, 330, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonAllowance.setFont(font)
        self.radioButtonAllowance.setStyleSheet("color: rgb(11, 37, 114);")
        self.radioButtonAllowance.setObjectName("radioButtonAllowance")
        self.radioButtonOthers = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonOthers.setGeometry(QtCore.QRect(540, 330, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonOthers.setFont(font)
        self.radioButtonOthers.setStyleSheet("color: rgb(11, 37, 114);")
        self.radioButtonOthers.setObjectName("radioButtonOthers")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(150, 360, 113, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSave.setGeometry(QtCore.QRect(370, 360, 113, 51))
        self.pushButtonSave.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(570, 360, 113, 51))
        self.pushButtonClose.setStyleSheet("/* Tùy chỉnh cho QTabWidget */\n"
"QTabWidget::pane {\n"
"    border: none; /* Xóa viền của QTabWidget */\n"
"    background-color: transparent; /* Nền trong suốt */\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #4e79b0, stop:1 #1e5fa1); /* Gradient nền của tab */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #1e5fa1; /* Viền tab */\n"
"    border-radius: 12px; /* Bo tròn góc của tab */\n"
"    padding: 12px; /* Khoảng cách giữa văn bản và viền */\n"
"    margin-right: 6px; /* Khoảng cách giữa các tab */\n"
"    font-size: 14px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của tab khi chọn */\n"
"    border-color: #1abc9c; /* Viền của tab khi chọn */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của tab khi hover */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các nút */\n"
"QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #3498db, stop:1 #2980b9); /* Gradient nền của nút */\n"
"    color: white; /* Màu chữ */\n"
"    border: 2px solid #2980b9; /* Viền của nút */\n"
"    border-radius: 15px; /* Bo tròn góc của nút */\n"
"    padding: 15px 30px; /* Khoảng cách giữa văn bản và viền */\n"
"    font-size: 16px; /* Kích thước font chữ */\n"
"    font-weight: bold; /* Làm cho chữ đậm */\n"
"    transition: background-color 0.3s, border-color 0.3s, color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền của nút khi hover */\n"
"    color: white; /* Màu chữ khi hover */\n"
"    border-color: #16a085; /* Viền của nút khi hover */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #16a085, stop:1 #1abc9c); /* Gradient nền của nút khi nhấn */\n"
"    border-color: #1abc9c; /* Viền của nút khi nhấn */\n"
"    color: white; /* Màu chữ khi nhấn */\n"
"    transform: scale(0.98); /* Tạo hiệu ứng co lại khi nhấn */\n"
"}\n"
"\n"
"/* Tùy chỉnh cho các tab khi không chọn */\n"
"QTabBar::tab:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #34495e, stop:1 #2c3e50); /* Gradient nền cho tab chưa chọn */\n"
"    border-color: #2c3e50; /* Viền cho tab chưa chọn */\n"
"    color: #ecf0f1; /* Màu chữ cho tab chưa chọn */\n"
"}\n"
"\n"
"/* Đảm bảo rằng tab có hiệu ứng khi hover */\n"
"QTabBar::tab:hover:!selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #1abc9c, stop:1 #16a085); /* Gradient nền khi hover vào tab chưa chọn */\n"
"    border-color: #16a085;\n"
"}\n"
"\n"
"")
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(290, 170, 341, 31))
        self.dateEdit.setStyleSheet("QDateEdit {\n"
"    background-color: #f0f0f0; /* Màu nền mặc định */\n"
"    border: 2px solid #0066cc; /* Viền mặc định */\n"
"    border-radius: 10px; /* Bo góc */\n"
"    padding: 5px; /* Khoảng cách bên trong */\n"
"    color: #333; /* Màu chữ */\n"
"    font-size: 16px; /* Kích thước chữ */\n"
"    transition: background-color 0.3s, border-color 0.3s; /* Hiệu ứng chuyển màu */\n"
"}\n"
"\n"
"QDateEdit:hover {\n"
"    background-color: #a5d6a7; /* Màu nền khi hover (xanh lá nhạt) */\n"
"    border-color: #66bb6a; /* Màu viền khi hover (xanh lá) */\n"
"}\n"
"\n"
"QDateEdit:focus {\n"
"    background-color: #c8e6c9; /* Màu nền khi focus (xanh lá nhạt) */\n"
"    border-color: #388e3c; /* Màu viền khi focus (xanh lá đậm) */\n"
"}\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.label_8.raise_()
        self.label.raise_()
        self.pushButton1.raise_()
        self.pushButton2.raise_()
        self.pushButton3.raise_()
        self.lineEditAmount.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.radioButtonSalary.raise_()
        self.radioButtonAllowance.raise_()
        self.radioButtonOthers.raise_()
        self.pushButtonClear.raise_()
        self.pushButtonSave.raise_()
        self.pushButtonClose.raise_()
        self.dateEdit.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "Amount:"))
        self.label_6.setText(_translate("MainWindow", "Date:"))
        self.label_7.setText(_translate("MainWindow", "Category:"))
        self.radioButtonSalary.setText(_translate("MainWindow", "Salary"))
        self.radioButtonAllowance.setText(_translate("MainWindow", "Allowance"))
        self.radioButtonOthers.setText(_translate("MainWindow", "Others"))
        self.pushButtonClear.setText(_translate("MainWindow", "Clear "))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
